# Generated by Django 3.1.4 on 2020-12-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactForm',
            new_name='evaluateForm',
        ),
    ]
