# Generated by Django 3.1.2 on 2020-12-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201206_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evaluateForm',
        ),
    ]
